# Generated by Django 3.1.4 on 2020-12-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('image_order',)},
        ),
        migrations.AddField(
            model_name='image',
            name='image_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
